const ROLE_ENUM = {
    ROLE_USER: 'ROLE_USER',
    ROLE_DONATOR: 'ROLE_DONATOR',
    ROLE_DEV: 'ROLE_DEV',
    ROLE_MODERATOR: 'ROLE_MODERATOR',
    ROLE_ADMIN: 'ROLE_ADMIN',
    ROLE_SUPERADMIN: 'ROLE_SUPERADMIN',
}

module.exports = ROLE_ENUM;
